services:
  postgres:
    image: postgis/postgis
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - postgres

  api:
    image: pedrohsalmeida/spotsat-back
    env_file:
      - .env
    ports:
      - "${PORT_API}:${PORT_API_INTERNAL}"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: pedrohsalmeida/spotsat-front
    env_file:
      - .env
    ports:
      - "${PORT_FRONT}:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:${PORT_API}
      - HOST=0.0.0.0
      - PORT=3000